version: '3'
services:

    web:
        container_name: web
        build:
            context: ./
            dockerfile: Dockerfile-web
        volumes:
            - ./:/var/www
        ports:
            - "8081:80"
        depends_on:
            - app

    app:
        container_name: app
        build:
            context: ./
            dockerfile: Dockerfile-app
        volumes:
            - ./:/var/www
        depends_on:
              - db
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"

    db:
        container_name: db
        image: mysql:5.7.17
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=oauth"
        ports:
            - "33062:3306"
